CREATE TABLE IF NOT EXISTS users
(
    id    int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  varchar(100) NOT NULL,
    email varchar(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS categories
(
    id   int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS events
(
    id                   int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                varchar(120) NOT NULL,
    annotation           text         NOT NULL,
    description          text,
    state                varchar(20)  NOT NULL,
    creation_date        timestamp    NOT NULL,
    event_date           timestamp    NOT NULL,
    publication_date     timestamp,
    paid                 bool         NOT NULL,
    participant_limit    int4 DEFAULT 0,
    requested_moderation bool DEFAULT true,
    latitude             float8,
    longitude            float8,
    category_id          int8 REFERENCES categories (id) ON DELETE RESTRICT,
    creator_id           int8         REFERENCES users (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS participation_requests
(
    id             int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creation_date  timestamp   NOT NULL,
    status         varchar(20) NOT NULL,
    event_id       int8 REFERENCES events (id) ON DELETE CASCADE,
    participant_id int8 REFERENCES users (id) ON DELETE CASCADE
);